"use client"
import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import { galleryApi } from '@/lib/api/gallery'
import { Card, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { ArrowRight, ImageIcon } from 'lucide-react'

export default function GalleryPage() {
  const [projects, setProjects] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    galleryApi.getPublicProjects()
      .then(data => setProjects(data.items || data))
      .catch(err => setError('Failed to load gallery projects.'))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="container px-4 py-24 min-h-screen">
      <div className="text-center mb-16">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">Research Gallery</h1>
        <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
          Explore spatial design outputs generated by the ArchAI-Plan multi-agent architecture.
        </p>
      </div>

      {error && (
        <div className="p-4 bg-destructive/10 text-destructive text-center rounded-lg max-w-2xl mx-auto mb-8">
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-center py-20">Loading...</div>
      ) : !projects || projects.length === 0 ? (
        <div className="text-center py-20 bg-card/20 rounded-xl border border-border/50 max-w-4xl mx-auto">
          <ImageIcon className="w-16 h-16 text-muted-foreground/30 mx-auto mb-4" />
          <h3 className="text-xl font-medium mb-2">No Projects Published Yet</h3>
          <p className="text-muted-foreground">Admin needs to publish projects from the dashboard.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project) => (
            <Link key={project.id} href={`/gallery/${project.slug}`}>
              <Card className="h-full overflow-hidden flex flex-col group bg-card/40 hover:bg-card/60 transition-all border-border/50 hover:border-primary/50">
                <div className="aspect-[4/3] bg-muted relative overflow-hidden">
                  {project.cover_image_url ? (
                    <img 
                      src={project.cover_image_url} 
                      alt={project.title} 
                      className="object-cover w-full h-full group-hover:scale-105 transition-transform duration-500"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center bg-card">
                      <ImageIcon className="w-12 h-12 text-muted-foreground/30" />
                    </div>
                  )}
                  {project.featured && (
                    <div className="absolute top-4 left-4">
                      <Badge variant="default" className="bg-primary text-primary-foreground">Featured</Badge>
                    </div>
                  )}
                </div>
                <CardContent className="p-6 flex-1 flex flex-col">
                  <div className="flex items-center justify-between mb-3">
                    <Badge variant="outline" className="text-xs">{project.category || 'Uncategorized'}</Badge>
                    {project.project_date && <span className="text-xs text-muted-foreground">{project.project_date}</span>}
                  </div>
                  <h3 className="text-xl font-bold mb-2 group-hover:text-primary transition-colors">{project.title}</h3>
                  <p className="text-muted-foreground text-sm line-clamp-3 mb-6 flex-1">
                    {project.short_description || project.description}
                  </p>
                  
                  <div className="flex flex-wrap gap-2 mb-6 mt-auto">
                    {project.related_components?.map((comp: string) => (
                      <Badge key={comp} variant="secondary" className="text-[10px] bg-secondary/50">
                        {comp}
                      </Badge>
                    ))}
                  </div>
                  
                  <div className="flex items-center text-sm font-medium text-primary">
                    View Project <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
                  </div>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      )}
    </div>
  )
}
