"""
ArchAI-Plan Initial Database Migration
Auto-generated by Alembic
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = '001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # users
    op.create_table(
        'users',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('email', sa.String(255), nullable=False, unique=True),
        sa.Column('password_hash', sa.String(512), nullable=False),
        sa.Column('role', sa.String(50), server_default='admin', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='1'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)

    # gallery_projects
    op.create_table(
        'gallery_projects',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('slug', sa.String(255), nullable=False, unique=True),
        sa.Column('short_description', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(100), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('related_components', sa.JSON(), nullable=True),
        sa.Column('project_date', sa.String(50), nullable=True),
        sa.Column('cover_image', sa.String(500), nullable=True),
        sa.Column('featured', sa.Boolean(), server_default='0'),
        sa.Column('published', sa.Boolean(), server_default='0'),
        sa.Column('sort_order', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_gallery_projects_slug', 'gallery_projects', ['slug'], unique=True)
    op.create_index('ix_gallery_projects_published', 'gallery_projects', ['published'])
    op.create_index('ix_gallery_projects_featured', 'gallery_projects', ['featured'])

    # gallery_images
    op.create_table(
        'gallery_images',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), sa.ForeignKey('gallery_projects.id', ondelete='CASCADE'), nullable=False),
        sa.Column('image_path', sa.String(500), nullable=False),
        sa.Column('alt_text', sa.String(255), nullable=True),
        sa.Column('sort_order', sa.Integer(), server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_gallery_images_project_id', 'gallery_images', ['project_id'])

    # contact_messages
    op.create_table(
        'contact_messages',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('phone', sa.String(50), nullable=True),
        sa.Column('subject', sa.String(255), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), server_default='0'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_contact_messages_is_read', 'contact_messages', ['is_read'])

    # projects
    op.create_table(
        'projects',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('current_component', sa.String(50), nullable=True),
        sa.Column('master_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )

    # component_runs
    op.create_table(
        'component_runs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), sa.ForeignKey('projects.id', ondelete='CASCADE'), nullable=False),
        sa.Column('component_name', sa.String(50), nullable=False),
        sa.Column('status', sa.String(20), server_default='pending'),
        sa.Column('input_json', sa.JSON(), nullable=True),
        sa.Column('output_json', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
    )
    op.create_index('ix_component_runs_project_id', 'component_runs', ['project_id'])

    # project_outputs
    op.create_table(
        'project_outputs',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('project_id', sa.String(36), sa.ForeignKey('projects.id', ondelete='CASCADE'), nullable=False),
        sa.Column('component_name', sa.String(50), nullable=False),
        sa.Column('output_type', sa.String(20), nullable=False),
        sa.Column('file_path', sa.String(500), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_project_outputs_project_id', 'project_outputs', ['project_id'])

    # site_settings
    op.create_table(
        'site_settings',
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('setting_key', sa.String(100), nullable=False, unique=True),
        sa.Column('setting_value', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index('ix_site_settings_setting_key', 'site_settings', ['setting_key'], unique=True)

    # Keep optional public contact settings blank until an administrator configures them.
    op.bulk_insert(
        sa.table(
            'site_settings',
            sa.column('id', sa.String),
            sa.column('setting_key', sa.String),
            sa.column('setting_value', sa.String),
        ),
        [
            {'id': 'contact-email-setting', 'setting_key': 'contact_email', 'setting_value': ''},
            {'id': 'contact-phone-setting', 'setting_key': 'contact_phone', 'setting_value': ''},
            {'id': 'contact-address-setting', 'setting_key': 'contact_address', 'setting_value': ''},
            {'id': 'site-description-setting', 'setting_key': 'site_description', 'setting_value': ''},
            {'id': 'facebook-url-setting', 'setting_key': 'facebook_url', 'setting_value': ''},
            {'id': 'linkedin-url-setting', 'setting_key': 'linkedin_url', 'setting_value': ''},
        ]
    )


def downgrade() -> None:
    op.drop_table('site_settings')
    op.drop_table('project_outputs')
    op.drop_table('component_runs')
    op.drop_table('projects')
    op.drop_table('contact_messages')
    op.drop_table('gallery_images')
    op.drop_table('gallery_projects')
    op.drop_table('users')

